pixel_perfect/images/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from images.views import (
    DeleteImageView,
    DownloadImageView,
    EnhanceImageView,
    FullEnhancementView,
    GoogleDriveUploadView,
    ImageGalleryView,
    UpscaleImageView,
    TrackTaskView,
)

urlpatterns = [
    path("upscale/", UpscaleImageView.as_view(), name="upscale"),
    path("enhance/", EnhanceImageView.as_view(), name="enhance"),
    path("full-enhancement/", FullEnhancementView.as_view(), name="full_enhancement"),
    path("list/", ImageGalleryView.as_view(), name="images_list"),
    path('track/', TrackTaskView.as_view()),
    path("download/<int:pk>", DownloadImageView.as_view(), name="save"),
    path("send-image/<int:pk>", GoogleDriveUploadView.as_view(), name="upload"),
    path("delete-image/", DeleteImageView.as_view(), name="delete_image"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixel_perfect/pixel_perfect/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("users.urls")),
        path("images/", include("images.urls")),
        path("accounts/", include("allauth.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

handler404 = 'pixel_perfect.handlers.Custom404Handler'
handler500 = 'pixel_perfect.handlers.Custom500Handler'

pixel_perfect/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
    PasswordChangeView,
    TemplateView,
)

from django.urls import path
from users.views import (
    ContactView,
    CustomLoginView,
    DeleteUserView,
    OAuth2GoogleDriveAccessCallbackView,
    OAuth2GoogleDriveAccessView,
    ProfileView,
    RedirectInvalidLoginView,
    UserRegisterView,
    PasswordChangeDoneCustomView,
)

urlpatterns = [
    path("", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("delete/profile/", DeleteUserView.as_view(), name="delete_profile"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("authorize/", OAuth2GoogleDriveAccessView.as_view(), name="authorize"),
    path("oauth2callback/", OAuth2GoogleDriveAccessCallbackView.as_view(), name="callback"),
    path("accounts/social/signup/", RedirectInvalidLoginView.as_view(), name="signup_redirect"),
    path("dashboard/", TemplateView.as_view(template_name="pixel_perfect/dashboard.html"), name="dashboard"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("password_reset/",
         PasswordResetView.as_view(template_name="users/registration/password_reset.html"),
         name="password_reset"),
    path("password_reset/done",
         PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"),
         name="password_reset_done"),
    path("password_reset/<uidb64>/<token>",
         PasswordResetConfirmView.as_view(template_name="users/registration/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path("password_reset/complete",
         PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"),
         name="password_reset_complete"),
    path("accounts/password/change/",
         PasswordChangeView.as_view(template_name="users/change_password.html"),
         name="account_change_password"),
    path("accounts/password/change/done",
         PasswordChangeDoneCustomView.as_view(),
         name="password_change_done")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixel_perfect/images/models.py
from django.contrib.auth.models import User
from django.db import models


class EnhancedImages(models.Model):
    img_name = models.CharField(max_length=100, null=False)
    img_path = models.ImageField(null=True)
    img_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(null=False, auto_now=True)

    def __str__(self):
        return self.img_name

pixel_perfect/images/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

from images.validators import ImageValidator


class UpscaleImagesForm(forms.Form):
    img_path = forms.ImageField(
        validators=[
            ImageValidator(size=3145728, width=2400, height=1440),
            FileExtensionValidator(["jpg", "jpeg", "png"]),
        ]
    )

    upscale_method = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"class": "form-check form-check-inline radiobtn"}),
        choices=[("espcn", "ESPCN"), ("fsrcnn", "FSRCNN"), ("edsr", "EDSR"), ("lapsrn", "LapSRN")],
    )

    upscale_size = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"class": "form-check form-check-inline"}),
        choices=[(2, "x2"), (3, "x3"), (4, "x4")],
    )

    do_compress = forms.BooleanField(
        required=False,
        label="[Optional] Compress image size",
        widget=forms.CheckboxInput(attrs={"class": "custom-control-input"}),
    )

    compress_q_factor = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"type": "range", "step": "1", "min": "30", "max": "95", "class": "form-control"}
        ),
        required=False,
    )


class EnhanceImagesForm(forms.Form):
    img_path = forms.ImageField(
        validators=[
            ImageValidator(size=3145728, width=2400, height=1440),
            FileExtensionValidator(["jpg", "jpeg", "png"]),
        ]
    )

    image_type = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"class": "form-check form-check-inline"}),
        choices=[("color", "RGB IMAGE"), ("color_real", "REAL WORLD RGB IMAGE"), ("greyscale", "GREYSCALE")],
    )

    quality_factor = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"type": "range", "step": "1", "min": "30", "max": "90", "class": "form-control"}
        ),
        required=False,
    )

pixel_perfect/images/views.py
import os

import google.oauth2.credentials
from celery.result import AsyncResult
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import DeleteView, FormView
from django.views.generic.list import ListView
from image_processing import config
from image_processing.img_processing import ImgProcesses
from images.celery_tasks import upscale_image_task, enhance_image_task, image_restoration_task
from images.forms import EnhanceImagesForm, UpscaleImagesForm
from images.models import EnhancedImages
from users.gdrive import drive_manager
from users.mixins import CustomLoginRequiredMixin
from billiard.exceptions import WorkerLostError


class UpscaleImageView(CustomLoginRequiredMixin, FormView):
    template_name = "images/upscale-image.html"
    form_class = UpscaleImagesForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            img_file = request.FILES.get("img_path")
            model = form.cleaned_data.get("upscale_method")
            scale = form.cleaned_data.get("upscale_size")

            filename, _ = os.path.splitext(img_file.name)

            save_as_name = f"{filename}_{model}_x{scale}.jpeg"
            save_to_path = os.path.join(settings.BASE_DIR, config.upscaled_img_path, str(request.user.id))
            image_path = os.path.join(save_to_path, save_as_name)

            ImgProcesses.img_write_from_memory(file=img_file, save_to_path=image_path)

            upscale_params = {
                "src_image_path": image_path,
                "cnn_model": model,
                "scale": int(scale),
                "do_compress": form.cleaned_data.get("do_compress"),
                "quality_factor": form.cleaned_data.get("compress_q_factor"),
            }

            upscale_task = upscale_image_task.delay(upscale_params, request.user.id)
            return JsonResponse({"form_valid": True, 'task_id': upscale_task.id})

        return JsonResponse({"form_valid": False})


class EnhanceImageView(CustomLoginRequiredMixin, FormView):
    template_name = "images/enhance-image.html"
    form_class = EnhanceImagesForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            img_file = request.FILES.get("img_path")
            model = form.cleaned_data.get("image_type")

            filename, _ = img_file.name.split('.')

            save_as_name = f"{filename}_{model}.jpeg"
            save_to_path = os.path.join(settings.BASE_DIR, config.enhanced_img_path, str(request.user.id))
            image_path = os.path.join(save_to_path, save_as_name)

            ImgProcesses.img_write_from_memory(file=img_file, save_to_path=image_path)

            enhance_params = {
                "src_image_path": image_path,
                "img_type": model,
                "enhance_qfactor": int(request.POST.get("quality_factor")),
            }

            enhance_task = enhance_image_task.delay(enhance_params, request.user.id)

            return JsonResponse({"form_valid": True, 'task_id': enhance_task.id})
        return JsonResponse({"form_valid": False})


class FullEnhancementView(CustomLoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        upscale_form = UpscaleImagesForm()
        enhance_form = EnhanceImagesForm()

        context = {
            "upscale_form": upscale_form,
            "enhance_form": enhance_form,
        }
        return render(request, template_name="images/total-enhancement-image.html", context=context)

    def post(self, request, *args, **kwargs):
        upscale_form = UpscaleImagesForm(self.request.POST, self.request.FILES)
        enhance_form = EnhanceImagesForm(self.request.POST, self.request.FILES)

        if upscale_form.is_valid() and enhance_form.is_valid():
            img_file = request.FILES.get("img_path")
            model = enhance_form.cleaned_data.get("image_type")
            scale = upscale_form.cleaned_data.get("upscale_size")

            filename, _ = img_file.name.split('.')

            save_as_name = f"{filename}_{model}_x{scale}.jpeg"
            save_to_path = os.path.join(settings.BASE_DIR, config.enhanced_img_path, str(request.user.id))
            image_path = os.path.join(save_to_path, save_as_name)

            ImgProcesses.img_write_from_memory(file=img_file, save_to_path=image_path)

            upscale_params = {
                "src_image_path": image_path,
                "cnn_model": upscale_form.cleaned_data.get("upscale_method"),
                "scale": int(scale),
                "do_compress": upscale_form.cleaned_data.get("do_compress"),
                "quality_factor": upscale_form.cleaned_data.get("compress_q_factor"),
            }

            enhance_params = {
                "src_image_path": image_path,
                "img_type": model,
                "enhance_qfactor": int(request.POST.get("quality_factor")),
            }

            restore_image_task = image_restoration_task.delay(upscale_params, enhance_params, request.user.id)

            return JsonResponse({"form_valid": True, 'task_id': restore_image_task.id})
        return JsonResponse({"form_valid": False})


class ImageGalleryView(CustomLoginRequiredMixin, ListView):
    template_name = "images/images-list.html"
    model = EnhancedImages
    context_object_name = "images"
    paginate_by = 6

    def get_queryset(self):
        return EnhancedImages.objects.filter(img_owner=self.request.user.id).order_by('-date_created')


class TrackTaskView(View):
    def get(self, request):
        task_id = request.GET.get("task_id")
        result_wrapper = AsyncResult(task_id)

        try:
            return JsonResponse({"status": result_wrapper.status, 'result': result_wrapper.result})
        except TypeError:
            return JsonResponse({"status": 'ABORTED'})


class DeleteImageView(CustomLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = EnhancedImages
    success_url = reverse_lazy("images_list")
    success_message = "Image has been deleted successfully."

    def get_object(self, queryset=None):
        return EnhancedImages.objects.get(pk=self.request.GET.get("img_id"))


class GoogleDriveUploadView(CustomLoginRequiredMixin, View):
    def get(self, request, pk):
        image_db = get_object_or_404(EnhancedImages, pk=pk, img_owner=request.user.id)

        if not request.session.get("credentials", False):
            request.session["img_id"] = pk
            return redirect("authorize")

        credentials = google.oauth2.credentials.Credentials(**request.session["credentials"])

        file_path = f'{settings.BASE_DIR}' + image_db.img_path.url

        params = {
            "src_image": file_path,
            "save_image_name": image_db.img_name,
            "mime_type": "image/jpeg",
            "folder_id": drive_manager.get_gdrive_folder_id(credentials),
        }

        drive_manager.uploadImage(credentials=credentials, **params)

        if request.session.get("img_id", None):
            request.session.pop("img_id")

        messages.success(request, "Image successfully saved to Google Drive!")
        return redirect("images_list")


class DownloadImageView(CustomLoginRequiredMixin, View):
    def get(self, request, pk):
        image_db = get_object_or_404(EnhancedImages, pk=pk, img_owner=request.user.id)
        img_url = f'{settings.BASE_DIR}' + image_db.img_path.url

        response = FileResponse(open(img_url, "rb"), as_attachment=True)
        return response

pixel_perfect/images/templates/images/enhance-image.html
{% extends 'pixel_perfect/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'images/css/loading_spinner.css' %}">
{% endblock %}

{% block content %}

    <div id="messageContainer" class="container-fluid w-50 mt-3" style="display: none">
        <div id="message" class="alert alert-danger text-center center-block">

        </div>
    </div>

    <div class="col-xl-12 d-flex justify-content-center">


        <div class="form-group mt-5" style="width: 40%">
            <form method="POST" enctype="multipart/form-data" id="image_form">
                {% csrf_token %}

                <h2 class="heading text-center" style="margin-bottom: 50px">1. Choose image:</h2>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputFile1">Upload</span>
                    </div>
                    <div class="custom-file">
                        {{ form.img_path }}
                        <label class="custom-file-label" for="id_img_path">Choose file</label>
                    </div>

                </div>

                <h2 class="heading text-center " style="margin: 50px 0;">2. Select type of the image:</h2>

                <fieldset class="d-flex justify-content-center" style="margin: 5% 0 8%;">
                    {% for radio in form.image_type %}
                    <div class="radio-toolbar" style="display: inline">
                        {{ radio }}
                    </div>
                    {% endfor %}
                </fieldset>

                <h2 class="heading text-center" style="margin-bottom: 50px">3. AI Enhance Factor:</h2>

                    {{ form.quality_factor }}

                <br>
            <div class="d-flex justify-content-between">
                <input type="submit" value="Process" onclick="show_modal()" class="btn btn-info btn-rounded mb-4"
                       id="submit" style="width:47%; border-radius: 40px;" disabled>
                <button type="button" class="btn btn-info btn-rounded mb-4" id="toggleModal"
                        style="width:47%; border-radius: 40px;"
                        data-toggle="modal" data-target="#imageWindowModal" disabled>
                    See result
                </button>
            </div>
            </form>
        </div>
    </div>


    <div class="modal fade" id="imageWindowModal" tabindex="-1">

        <div class="modal-dialog modal-lg" role='document' id="image-modal">
            <div class="modal-content h-60">
                <div class="d-flex align-items-center bg-dark">
                    <img id="new-image" src="" class="img-fluid mr-auto ml-auto" style="height: 60vh">
                </div>
                <div class="modal-footer bg-dark">
                    <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Close</button>
                    <a href="#" type="button" class="btn btn-info ml-auto" id="download">Download</a>
                    <a href="#" type="button" class="btn btn-primary" id="saveGDrive"><img class="mr-2" src="{% static 'users/assets/images/g_drive_icon.png' %}" style="width: 15%;">Google Drive</a>
                </div>
            </div>
        </div>
    <div id="loader" style="align-items: center;">
        <div class="loader text-center">
            <div class="loading ml-auto mr-auto">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="loader-message m-5 bg-dark rainbow-text">
                <h2 class="font-weight-bold">Please wait while we do our magic!</h2>
            </div>
        </div>
    </div>
    </div>

    <script src="{% static 'images/js/form_validation.js' %}"></script>
    <script src="{% static 'images/js/fetch_image.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>

    <script type="application/javascript">
        $('input[type="file"]').change(function(e){
            var fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
            document.getElementById('inputFile1').classList.add('gradient-background')});
    </script>

{% endblock %}

pixel_perfect/images/templates/images/total-enhancement-image.html
{% extends 'pixel_perfect/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'images/css/loading_spinner.css' %}">
{% endblock %}

{% block content %}

<div id="messageContainer" class="container-fluid mt-3" style="display: none">
    <div id="message" class="alert alert-danger text-center center-block">

    </div>
</div>

<div class="col-xl-12 d-flex justify-content-center">


    <div class="form-group mt-5 d-flex justify-content-center" style="width: 40%">
        <form method="POST" enctype="multipart/form-data" id="image_form">
            {% csrf_token %}

            <h2 class="heading text-center" style="margin-bottom: 50px">1. Choose image:</h2>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputFile1">Upload</span>
                </div>
                <div class="custom-file">
                    {{ upscale_form.img_path }}
                    <label class="custom-file-label" for="id_img_path">Choose file</label>
                </div>

            </div>

            <h2 class="heading text-center" style="margin: 50px 0;">2. Select upscale method:</h2>

            <fieldset class="d-flex justify-content-center" style="margin: 5% 0 8%;">
                {% for radio in upscale_form.upscale_method %}
                <div class="radio-toolbar" style="display: inline">
                    {{ radio }}
                </div>
                {% endfor %}
            </fieldset>

            <h2 class="heading text-center" style="margin-bottom: 50px">3. Determine the scale :</h2>

            <fieldset class="d-flex justify-content-center" style="margin: 5% 0;">
                {% for radio in upscale_form.upscale_size %}
                <div class="radio-toolbar " style="display: inline; margin: 0 10%;">
                    {{ radio }}
                </div>
                {% endfor %}
            </fieldset>
            <div class="custom-control custom-switch mb-3">

                {{ upscale_form.do_compress }}
                <label class="custom-control-label" for="id_do_compress" style="font-size: 1rem; color: #505050;">
                    {{ upscale_form.do_compress.label }}</label>

            </div>

            {{ upscale_form.compress_q_factor }}

            <h2 class="heading text-center" style="margin: 50px 0;">4. Select type of the image:</h2>

            <fieldset class="d-flex justify-content-center" style="margin: 5% 0 8%;">
                {% for radio in enhance_form.image_type %}
                <div class="radio-toolbar" style="display: inline">
                    {{ radio }}
                </div>
                {% endfor %}
            </fieldset>

            <h2 class="heading text-center" style="margin-bottom: 50px">5. AI Enhance Factor:</h2>

            {{ enhance_form.quality_factor }}
            <br>
            <div class="d-flex justify-content-between">
                <input type="submit" value="Process" onclick="show_modal()" class="btn btn-info btn-rounded mb-4"
                       id="submit" style="width:47%; border-radius: 40px;" disabled>
                <button type="button" class="btn btn-info btn-rounded mb-4" id="toggleModal"
                        style="width:47%; border-radius: 40px;"
                        data-toggle="modal" data-target="#imageWindowModal" disabled>
                    See result
                </button>
            </div>
        </form>
    </div>
</div>


<div class="modal fade" id="imageWindowModal" tabindex="-1">

    <div class="modal-dialog modal-lg" role='document' id="image-modal">
        <div class="modal-content h-60">
            <div class="d-flex align-items-center bg-dark">
                <img id="new-image" src="" class="img-fluid mr-auto ml-auto" style="height: 60vh">
            </div>
            <div class="modal-footer bg-dark">
                <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Close</button>
                    <a href="#" type="button" class="btn btn-info ml-auto" id="download">Download</a>
                    <a href="#" type="button" class="btn btn-primary" id="saveGDrive"><img class="mr-2" src="{% static 'users/assets/images/g_drive_icon.png' %}" style="width: 15%;">Google Drive</a>
            </div>
        </div>
    </div>
    <div id="loader" style="align-items: center;">
        <div class="loader text-center">
            <div class="loading ml-auto mr-auto">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="loader-message m-5 bg-dark rainbow-text">
                <h2 class="font-weight-bold">Please wait while we do our magic!</h2>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'images/js/form_validation.js' %}"></script>
<script src="{% static 'images/js/fetch_image.js' %}"></script>
<script src="{% static 'images/js/radio_btn_update.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>


<script type="application/javascript">
        $('input[type="file"]').change(function(e){
            var fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
            document.getElementById('inputFile1').classList.add('gradient-background');
        });



</script>

{% endblock %}

pixel_perfect/images/templates/images/upscale-image.html
{% extends 'pixel_perfect/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'images/css/loading_spinner.css' %}">
{% endblock %}

{% block content %}

<div id="messageContainer" class="container w-50 mt-3" style="display: none">
    <div id="message" class="alert alert-danger d-flex justify-content-center center-block">

    </div>
</div>

<div class="col-xl-12 d-flex justify-content-center">


    <div class="form-group mt-5" style="width: 40%">
        <form method="POST" enctype="multipart/form-data" id="image_form">
            {% csrf_token %}

            <h2 class="heading text-center" style="margin-bottom: 50px">1. Choose image:</h2>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputFile1">Upload</span>
                </div>
                <div class="custom-file">
                    {{ form.img_path }}
                    <label class="custom-file-label" for="id_img_path">Choose file</label>
                </div>

            </div>

            <h2 class="heading text-center" style="margin: 50px 0;">2. Select upscale method:</h2>

            <fieldset class="d-flex justify-content-center" style="margin: 5% 0 8%;">
                {% for radio in form.upscale_method %}
                <div class="radio-toolbar" style="display: inline">
                    {{ radio }}
                </div>
                {% endfor %}
            </fieldset>

            <h2 class="heading text-center" style="margin-bottom: 50px">3. Determine the scale :</h2>

            <fieldset class="d-flex justify-content-center" style="margin: 5% 0;">
                {% for radio in form.upscale_size %}
                <div class="radio-toolbar " style="display: inline; margin: 0 10%;">
                    {{ radio }}
                </div>
                {% endfor %}
            </fieldset>
            <div class="custom-control custom-switch">

                {{ form.do_compress }}
                <label class="custom-control-label" for="id_do_compress" style="font-size: 1rem; color: #505050;">
                    {{ form.do_compress.label }}</label>

            </div>

            {{ form.compress_q_factor }}

            <br>
            <div class="d-flex justify-content-between">
                <input type="submit" value="Process" onclick="show_modal()" class="btn btn-info btn-rounded mb-4"
                       id="submit" style="width:47%; border-radius: 40px;" disabled>
                <button type="button" class="btn btn-info btn-rounded mb-4" id="toggleModal"
                        style="width:47%; border-radius: 40px;"
                        data-toggle="modal" data-target="#imageWindowModal" disabled>
                    See result
                </button>
            </div>
        </form>
    </div>
</div>


<div class="modal fade" id="imageWindowModal" tabindex="-1">

    <div class="modal-dialog modal-lg" role='document' id="image-modal">
        <div class="modal-content h-60">
            <div class="d-flex align-items-center bg-dark">
                <img id="new-image" src="" class="img-fluid mr-auto ml-auto" style="height: 60vh">
            </div>
            <div class="modal-footer bg-dark">
                <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Close</button>
                    <a href="#" type="button" class="btn btn-info ml-auto" id="download">Download</a>
                    <a href="#" type="button" class="btn btn-primary" id="saveGDrive"><img class="mr-2" src="{% static 'users/assets/images/g_drive_icon.png' %}" style="width: 15%;">Google Drive</a>
            </div>
        </div>
    </div>
    <div id="loader" style="align-items: center;">
        <div class="loader text-center">
            <div class="loading ml-auto mr-auto">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="loader-message m-5 bg-dark rainbow-text">
                <h2 class="font-weight-bold">Please wait while we do our magic!</h2>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

<script src="{% static 'images/js/form_validation.js' %}"></script>
<script src="{% static 'images/js/fetch_image.js' %}"></script>
<script src="{% static 'images/js/radio_btn_update.js' %}"></script>


<script type="application/javascript">
            $('input[type="file"]').change(function(e){
                var fileName = e.target.files[0].name;
                $('.custom-file-label').html(fileName);
                document.getElementById('inputFile1').classList.add('gradient-background');
            });

</script>

{% endblock %}