pixel_perfect/pixel_perfect/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("users.urls")),
        path("images/", include("images.urls")),
        path("accounts/", include("allauth.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

handler404 = 'pixel_perfect.handlers.Custom404Handler'
handler500 = 'pixel_perfect.handlers.Custom500Handler'

pixel_perfect/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
    PasswordChangeView,
    TemplateView,
)

from django.urls import path
from users.views import (
    ContactView,
    CustomLoginView,
    DeleteUserView,
    OAuth2GoogleDriveAccessCallbackView,
    OAuth2GoogleDriveAccessView,
    ProfileView,
    RedirectInvalidLoginView,
    UserRegisterView,
    PasswordChangeDoneCustomView,
)

urlpatterns = [
    path("", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("delete/profile/", DeleteUserView.as_view(), name="delete_profile"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("authorize/", OAuth2GoogleDriveAccessView.as_view(), name="authorize"),
    path("oauth2callback/", OAuth2GoogleDriveAccessCallbackView.as_view(), name="callback"),
    path("accounts/social/signup/", RedirectInvalidLoginView.as_view(), name="signup_redirect"),
    path("dashboard/", TemplateView.as_view(template_name="pixel_perfect/dashboard.html"), name="dashboard"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("password_reset/",
         PasswordResetView.as_view(template_name="users/registration/password_reset.html"),
         name="password_reset"),
    path("password_reset/done",
         PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"),
         name="password_reset_done"),
    path("password_reset/<uidb64>/<token>",
         PasswordResetConfirmView.as_view(template_name="users/registration/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path("password_reset/complete",
         PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"),
         name="password_reset_complete"),
    path("accounts/password/change/",
         PasswordChangeView.as_view(template_name="users/change_password.html"),
         name="account_change_password"),
    path("accounts/password/change/done",
         PasswordChangeDoneCustomView.as_view(),
         name="password_change_done")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixel_perfect/users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username}"

pixel_perfect/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput
from django.utils.safestring import mark_safe
from users.models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ["username", "email", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    def clean(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                mark_safe(
                    f"An account with email address {email} already exists. <br>"
                    f"Please login using this email or choose different email address."
                )
            )
        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email"]

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields["email"].required = True


class MyClearableFileInput(ClearableFileInput):
    initial_text = ""
    input_text = ""


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]
        widgets = {"image": MyClearableFileInput}


class ContactForm(forms.Form):
    name = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={"placeholder": "Name"}))
    email = forms.EmailField(
        required=True, label="Email Address", widget=forms.EmailInput(attrs={"placeholder": "Email"})
    )
    subject = forms.ChoiceField(
        choices=[
            ("General", "General"),
            ("Support", "Technical Support"),
            ("Bug Report", "Bug Report"),
            ("Feedback", "Feedback"),
            ("Suggestion", "Suggestions"),
        ]
    )
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={"placeholder": "Write your message here"}))

pixel_perfect/users/views.py
from __future__ import annotations

import os.path

import google_auth_oauthlib
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.generic.edit import DeleteView, FormView
from oauthlib.oauth2.rfc6749.errors import AccessDeniedError
from users.forms import ContactForm, ProfileUpdateForm, UserRegisterForm, UserUpdateForm
from users.mixins import CustomLoginRequiredMixin


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = "users/login.html"
    success_message = "You were successfully logged in."
    redirect_authenticated_user = True


class DeleteUserView(CustomLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    success_url = reverse_lazy("login")
    success_message = "Your account has been deleted."
    permission_denied_message = "You need to be logged in to view this page. Please login or register!"

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)

    def delete(self, request, *args, **kwargs):
        messages.info(self.request, self.success_message)
        return super(DeleteUserView, self).delete(request, *args, **kwargs)


class ProfileView(CustomLoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"
    permission_denied_message = "You need to be logged in to view this page. Please login or register!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, pk=self.request.user.pk)
        context["date_joined"] = self.request.user.date_joined.strftime("%m/%d/%Y")
        context["user_form"] = UserUpdateForm(instance=user)
        context["profile_form"] = ProfileUpdateForm(instance=user.profile)
        return context

    def post(self, request, *args, **kwargs):
        user_form = UserUpdateForm(instance=request.user, data=self.request.POST)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect("profile")

        messages.error(request, "Something gone wrong. Try again!")
        return redirect("profile")


class RedirectInvalidLoginView(RedirectView):
    url = reverse_lazy("login")

    def get_redirect_url(self, *args, **kwargs):
        messages.info(self.request, "User with this email already exist. Please log in with email and password.")
        return super().get_redirect_url(*args, **kwargs)


class UserRegisterView(SuccessMessageMixin, CreateView):
    template_name = "users/registration/register.html"
    form_class = UserRegisterForm
    success_message = "Your profile was created successfully"

    def get_success_url(self):
        return reverse("login")


class PasswordChangeDoneCustomView(PasswordChangeDoneView):
    template_name = 'pixel_perfect/dashboard.html'

    def get(self, request, *args, **kwargs):
        messages.success(request, 'Your password has been changed!')
        return super().get(request, *args, **kwargs)


class OAuth2GoogleDriveAccessView(View):
    def get(self, request):
        credentials = settings.GOOGLE_CLIENT_CONFIG

        flow = google_auth_oauthlib.flow.Flow.from_client_config(
            credentials,
            scopes=["https://www.googleapis.com/auth/drive.file"],
            redirect_uri=settings.GOOGLE_OAUTH_REDIRECT_URI
        )

        authorization_url, state = flow.authorization_url(
            access_type="online", login_hint=request.user.email, include_granted_scopes="false"
        )

        request.session["state"] = state

        return redirect(authorization_url)


class OAuth2GoogleDriveAccessCallbackView(View):
    def get(self, request):
        state = request.session["state"]
        credentials = settings.GOOGLE_CLIENT_CONFIG

        flow = google_auth_oauthlib.flow.Flow.from_client_config(
            credentials, scopes=["https://www.googleapis.com/auth/drive.file"], state=state
        )

        flow.redirect_uri = settings.GOOGLE_OAUTH_REDIRECT_URI
        authorization_response = request.build_absolute_uri()

        try:
            flow.fetch_token(authorization_response=authorization_response)
        except AccessDeniedError:
            messages.info(request, message="Google Drive Authorization failed. Please try again!")
            return redirect(reverse("images_list"))

        credentials = flow.credentials

        request.session["credentials"] = {
            "token": credentials.token,
            "refresh_token": credentials.refresh_token,
            "token_uri": credentials.token_uri,
            "client_id": credentials.client_id,
            "client_secret": credentials.client_secret,
            "scopes": credentials.scopes,
        }

        return redirect(reverse("upload", kwargs={"pk": request.session.get("img_id")}))


class ContactView(SuccessMessageMixin, FormView):
    template_name = "users/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("contact")
    success_message = "Thank you for your feedback! Message sent successfully"

    def form_valid(self, form):
        send_mail(
            subject=form.cleaned_data.get("subject"),
            from_email=None,
            recipient_list=[os.environ["EMAIL"]],
            message=f'From: {form.cleaned_data.get("email")}\nMessage: {form.cleaned_data.get("message")}',
        )
        return super(ContactView, self).form_valid(form)

pixel_perfect/users/templates/users/change_password.html
{% extends 'pixel_perfect/base.html' %}
{% load socialaccount %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <div class="content-section d-flex justify-content-start ml-5 w-100">
        <div class="row align-items-center">
            <div class="col-lg-6 col-sm-12">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group col-md-11">
                    <legend class="border-bottom mb-4 align-items-start rainbow-text">Change Your Password</legend>
                    <h5 class="text-left">Would you like to change your password? <br><br> Enter your passsword below, and provide a new one, that you will use in the future to log in to your account!</h5>
                    <br>
                    {{ form|crispy }}

                    <div class="form-group">
                        <button class="btn btn-outline-info btn-rounded" type="submit">Change Password</button>
                    </div>
                </fieldset>
            </form>
            </div>
            <div class="col-lg-6 col-sm-12 d-flex justify-content-center">
                <img src="{% static 'users/assets/images/password_change.jpg' %}" style="width: 80%;">
            </div>
        </div>
    </div>
{% endblock %}

pixel_perfect/users/templates/users/contact.html
{% extends 'pixel_perfect/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="container w-100">
    <div class="row mt-4 mb-4 d-flex justify-content-center">
        <div class="col-lg-8 col-md-10 mx-auto text-center">
            <div class="page-heading ">
                <h1 class="rainbow-text">Contact Me</h1>
                <span class="subheading">Have questions? I have answers.</span>
            </div>
        </div>


        <div class="col-lg-8 col-md-10 mt-5 mx-auto">
            <p class="text-center">Want to get in touch? Fill out the form below to send me a message and I will get
                back to you as soon as possible!</p>

            <form name="sentMessage" id="contactForm" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-info btn-rounded w-50" id="sendMessageButton">Send</button>
                </div>
            </form>

        </div>
    </div>
    <hr>
</div>
{% endblock %}

pixel_perfect/users/templates/users/login.html
{% extends 'pixel_perfect/base.html' %}
{% load socialaccount %}
{% load crispy_forms_tags %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'users/css/slider.css' %}">
{% endblock %}

{% block content %}

    <section class="container-fluid" style="display: block; overflow: auto;">
        <div class="row">
            <div class="col-12 text-center welcome-text" style="width: 100% !important %">
                <img src="{% static 'pixel_perfect/assets/images/navbar-brand.png'%}" class="fostrap-logo" style="width: 30vw; padding-top: 2%"/>
                <h2 class="rainbow-text" style="padding-bottom: 1vh;">Where the magic exists!</h2>
                <div class="col-12 d-flex align-items-center justify-content-center  align-middle">
                    <h2 class="text-dark" style="margin-top: 20px; text-align: center;">Upscale your old images, decompress it's size and remove artifacts all in one place</h2>
                </div>
            </div>
        </div>
        <div class="row align-items-center" style="margin: 2% 0;">
            <div class=" col-md-12 col-lg-12 col-xl-8 h-100 d-inline-block">

                <div class="container d-flex align-items-center justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center h-100" style="padding-top: 2vh">
                    <div class=" juxtapose shadow img-fluid rounded">
                        <img src="{% static 'users/assets/images/before.png' %}" data-label="before">
                        <img src="{% static 'users/assets/images/after.jpg' %}" data-label="after">
                    </div>
                </div>

                </div>


            </div>
            <div class="col-md-12 col-lg-12 col-xl-4 d-inline-block d-flex align-items-center justify-content-center" style="height: 100%">
                <div class="d-inline-block shadow p-3 rounded">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form | crispy }}
                        </fieldset>

                        <div class="d-flex justify-content-around align-items-center mb-4">

                            <a href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>

                        <!-- Submit button -->
                        <input type="submit" class="btn btn-hover color-9 btn-lg btn-block" value="Sign in">
                        <a type="submit" href="{% url 'register' %}" class="btn btn-outline-info btn-lg btn-block" style="border-radius: 2rem;">Register</a>

                        <div class="divider align-items-center my-4">
                            <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
                        </div>
                        <a class="btn btn-outline-danger btn-lg btn-block btn-rounded" href="{% provider_login_url 'google' %}?next=/"
                           role="button" style="border-radius: 2rem;">
                            <img src="https://colorlib.com/etc/lf/Login_v9/images/icons/icon-google.png">
                            Continue with Google</a>

                    </form>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'users/js/slider.js'%}"></script>

{% endblock %}

pixel_perfect/users/templates/users/profile.html
{% extends 'pixel_perfect/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-section w-100 ml-5">
    <div class="row align-items-center border-bottom pb-3 mt-5" style="width: 95%">
        <div class="col-md-4 col-sm-12 mb-sm-5 d-flex justify-content-center">
            <img class="rounded-circle shadow-4 px-auto" src="{{ user.profile.image.url }}" style="width: 250px;">
        </div>

        <div class="col-md-8 col-sm-12 d-flex-block">
            <h2 class="text-dark">Hi, {{ user.username|title }}! </h2>
            <h3 class="text-dark">You’ve been with us since: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ date_joined }}.</h3>
            <br>
            <h5 class="text-muted">Email: {{ user.email }}</h5>
            <br>
        </div>
    </div>
</div>
<div class="row ml-5 my-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-12 col-xs-6 d-block">
            {{ user_form|crispy }}
        </div>
        <div class="col-12 d-block">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                </div>
                <div class="custom-file">
                    {{ profile_form }}
                    <label class="custom-file-label" for="id_image">Choose file</label>
                </div>

            </div>
            <button class="btn btn-outline-info" type="submit">Update</button>
            <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#profileDeleteModal"
                    style="float: right">Delete Account
            </button>
        </div>
    </form>
</div>

<div class="modal fade" id="profileDeleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-bold" id="exampleModalLongTitle">Please confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                All your images will be deleted permanently!
                <br>
                Would you like to continue?
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'delete_profile' %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Confirm">
                </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

<script type="application/javascript">
        $('input[type="file"]').change(function(e){
            var fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
            });

</script>

{% endblock %}